[build]
	framework = "astro"
	command   = "yarn run build"
	functions = "netlify/functions"
	publish   = "dist"

[dev]
	framework = "astro"
	command   = "yarn run dev"
	functions = "netlify/functions"
	port      = 3001
